#!/usr/bin/env python3
"""
SlackTracker — macOS menu bar + Touch Bar work timer.

- Start / Stop a timer from the Touch Bar or the menu bar (⏱ at the top of the screen).
- The display shows only the current period's elapsed time.
- Stopping the timer appends that period (start, end, duration) to ~/SlackWorkLog.md.
- A running period survives quitting/restarting the tracker.
- Double-tapping Command presents the Touch Bar controls.
"""

import os
import json
import threading
import subprocess
import ctypes
import signal
from datetime import datetime
from pathlib import Path
from time import monotonic

import rumps

# --- AppKit / pynput are optional but recommended ---
try:
    from AppKit import (
        NSPanel, NSColor, NSFont, NSScreen, NSApp,
        NSBackingStoreBuffered,
        NSFloatingWindowLevel, NSMakeRect,
        NSWindowStyleMaskBorderless,
        NSWindowCollectionBehaviorCanJoinAllSpaces,
        NSWindowCollectionBehaviorFullScreenAuxiliary,
        NSApplicationActivationPolicyAccessory,
        NSApplicationActivateIgnoringOtherApps, NSRunningApplication,
        NSEvent, NSEventMaskFlagsChanged, NSEventModifierFlagCommand,
    )
    from Foundation import NSObject
    import objc
    HAVE_APPKIT = True
except Exception:
    HAVE_APPKIT = False
    NSObject = object

try:
    from AppKit import (
        NSTouchBar, NSCustomTouchBarItem, NSButton, NSTextField,
        NSButtonTypeMomentaryPushIn, NSBezelStyleRounded,
    )
    HAVE_TOUCHBAR = True
except Exception:
    HAVE_TOUCHBAR = False

try:
    from pynput import keyboard as pkeyboard
    HAVE_PYNPUT = True
except Exception:
    HAVE_PYNPUT = False


HOME = Path.home()
LOG_FILE = HOME / "SlackWorkLog.md"
STATE_FILE = HOME / ".slacktracker_state.json"
FALLBACK_HOTKEY = "<ctrl>+<alt>+<cmd>+t"  # pynput fallback combo
CARBON_HOTKEY_KEYCODE = 17  # ANSI T
CARBON_HOTKEY_MODIFIERS = 0x0100 | 0x0800 | 0x1000  # cmdKey | optionKey | controlKey
DOUBLE_COMMAND_SECONDS = 0.45

GREEN = (0.15, 0.63, 0.34)
RED = (0.80, 0.22, 0.20)
GREY = (0.42, 0.42, 0.46)


def fmt_clock(seconds: int) -> str:
    """Compact clock for the menu bar / Touch Bar: 0:05:09."""
    h, rem = divmod(max(0, int(seconds)), 3600)
    m, s = divmod(rem, 60)
    return f"{h}:{m:02d}:{s:02d}"


def fmt_duration(seconds: int) -> str:
    h, rem = divmod(max(0, int(seconds)), 3600)
    m, s = divmod(rem, 60)
    if h:
        return f"{h}h {m:02d}m {s:02d}s"
    if m:
        return f"{m}m {s:02d}s"
    return f"{s}s"


def color(rgb):
    return NSColor.colorWithCalibratedRed_green_blue_alpha_(*rgb, 1.0)


def log_debug(message: str) -> None:
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{timestamp}] {message}", flush=True)


def last_day_heading(path: Path) -> str:
    """Return the most recent '## <date>' heading in the log, or ''."""
    try:
        for line in reversed(path.read_text(encoding="utf-8").splitlines()):
            if line.startswith("## "):
                return line[3:].strip()
    except Exception:
        pass
    return ""


def append_period(path: Path, start: datetime, end: datetime) -> int:
    """Append one timed period to the Markdown log; returns its duration in seconds."""
    seconds = max(0, int((end - start).total_seconds()))
    day = start.date().isoformat()
    end_fmt = "%H:%M:%S" if end.date() == start.date() else "%Y-%m-%d %H:%M:%S"

    new_file = not path.exists()
    with path.open("a", encoding="utf-8") as f:
        if new_file:
            f.write("# Work Log\n\nGenerated by SlackTracker.\n")
        if new_file or last_day_heading(path) != day:
            f.write(f"\n## {day}\n\n")
        f.write(
            f"- {start.strftime('%H:%M:%S')} → {end.strftime(end_fmt)} · "
            f"**{fmt_duration(seconds)}** ({seconds // 60} min)\n"
        )
    return seconds


# -------------------- Touch Bar host window --------------------

if HAVE_APPKIT:
    class KeyablePanel(NSPanel):
        """Invisible panel that can become key so AppKit shows its Touch Bar."""

        def canBecomeKeyWindow(self):
            return True

        def canBecomeMainWindow(self):
            return True
else:
    KeyablePanel = None


class TouchBarHost:
    """Invisible key-capable window used only to host Touch Bar content."""

    def __init__(self):
        self.panel = None
        if not HAVE_APPKIT:
            return
        self._build()

    def _build(self):
        screen = NSScreen.mainScreen().visibleFrame()
        rect = NSMakeRect(screen.origin.x, screen.origin.y, 1, 1)

        self.panel = KeyablePanel.alloc().initWithContentRect_styleMask_backing_defer_(
            rect, NSWindowStyleMaskBorderless, NSBackingStoreBuffered, False
        )
        self.panel.setLevel_(NSFloatingWindowLevel)
        self.panel.setOpaque_(False)
        self.panel.setBackgroundColor_(NSColor.clearColor())
        self.panel.setAlphaValue_(0.0)
        self.panel.setHasShadow_(False)
        self.panel.setReleasedWhenClosed_(False)
        self.panel.setHidesOnDeactivate_(False)
        try:
            self.panel.setIgnoresMouseEvents_(True)
        except Exception:
            pass
        self.panel.setCollectionBehavior_(
            NSWindowCollectionBehaviorCanJoinAllSpaces
            | NSWindowCollectionBehaviorFullScreenAuxiliary
        )

    def attach_touchbar(self, touch_bar) -> None:
        if self.panel is not None and hasattr(self.panel, "setTouchBar_"):
            self.panel.setTouchBar_(touch_bar)

    def present(self):
        if self.panel is None:
            log_debug("Touch Bar host unavailable")
            return
        try:
            NSApp.setActivationPolicy_(NSApplicationActivationPolicyAccessory)
            NSApp.activateIgnoringOtherApps_(True)
            NSRunningApplication.currentApplication().activateWithOptions_(
                NSApplicationActivateIgnoringOtherApps
            )
        except Exception:
            pass
        self.panel.orderFrontRegardless()
        self.panel.makeKeyAndOrderFront_(None)
        log_debug("Touch Bar host presented")


if HAVE_TOUCHBAR:
    class TouchBarController(NSObject):
        """Touch Bar with a period timer plus Start and Stop buttons."""

        TIMER_ID = "com.slacktracker.timer"
        START_ID = "com.slacktracker.start"
        STOP_ID = "com.slacktracker.stop"

        def initWithTracker_(self, tracker):
            self = objc.super(TouchBarController, self).init()
            if self is None:
                return None
            self.tracker = tracker
            self.label = None
            self.start_button = None
            self.stop_button = None
            self.touch_bar = NSTouchBar.alloc().init()
            self.touch_bar.setDelegate_(self)
            self.touch_bar.setDefaultItemIdentifiers_(
                [self.TIMER_ID, self.START_ID, self.STOP_ID]
            )
            return self

        def _make_button(self, title, action, rgb):
            button = NSButton.buttonWithTitle_target_action_(title, self, action)
            button.setButtonType_(NSButtonTypeMomentaryPushIn)
            button.setBezelStyle_(NSBezelStyleRounded)
            button.setFont_(NSFont.boldSystemFontOfSize_(15))
            try:
                button.setBezelColor_(color(rgb))
                button.setContentTintColor_(NSColor.whiteColor())
            except Exception:
                pass
            return button

        def touchBar_makeItemForIdentifier_(self, touch_bar, identifier):
            identifier = str(identifier)
            item = NSCustomTouchBarItem.alloc().initWithIdentifier_(identifier)
            if identifier == self.TIMER_ID:
                self.label = NSTextField.labelWithString_("⏱ 0:00:00")
                self.label.setFont_(
                    NSFont.monospacedDigitSystemFontOfSize_weight_(17, 0.4)
                )
                self.label.setTextColor_(NSColor.whiteColor())
                item.setView_(self.label)
            elif identifier == self.START_ID:
                self.start_button = self._make_button("▶ Start", "startPressed:", GREEN)
                item.setView_(self.start_button)
            elif identifier == self.STOP_ID:
                self.stop_button = self._make_button("■ Stop", "stopPressed:", RED)
                item.setView_(self.stop_button)
            else:
                return None
            self.update()
            return item

        def startPressed_(self, sender):
            self.tracker.start_timer(None)

        def stopPressed_(self, sender):
            self.tracker.stop_timer(None)

        def update(self):
            running = self.tracker.is_running
            if self.label is not None:
                prefix = "●" if running else "⏱"
                self.label.setStringValue_(
                    f"{prefix} {fmt_clock(self.tracker.elapsed())}"
                )
            if self.start_button is not None:
                self.start_button.setEnabled_(not running)
                try:
                    self.start_button.setBezelColor_(color(GREY if running else GREEN))
                except Exception:
                    pass
            if self.stop_button is not None:
                self.stop_button.setEnabled_(running)
                try:
                    self.stop_button.setBezelColor_(color(RED if running else GREY))
                except Exception:
                    pass

        def present(self):
            self.update()
            try:
                NSApp.setActivationPolicy_(NSApplicationActivationPolicyAccessory)
                NSApp.activateIgnoringOtherApps_(True)
                NSRunningApplication.currentApplication().activateWithOptions_(
                    NSApplicationActivateIgnoringOtherApps
                )
            except Exception:
                pass
            try:
                NSApp.setTouchBar_(self.touch_bar)
            except Exception:
                pass
            try:
                NSTouchBar.presentSystemModalFunctionBar_systemTrayItemIdentifier_(
                    self.touch_bar, self.TIMER_ID
                )
            except Exception:
                pass
            log_debug("Touch Bar present requested")
else:
    TouchBarController = None


# -------------------- App --------------------

class SlackTracker(rumps.App):
    def __init__(self):
        super().__init__("⏱", quit_button=None)
        if HAVE_APPKIT:
            try:
                NSApp.setActivationPolicy_(NSApplicationActivationPolicyAccessory)
                NSRunningApplication.currentApplication().hide()
            except Exception:
                pass
        self.status_item = rumps.MenuItem("Timer stopped")
        self.start_item = rumps.MenuItem("▶ Start Timer", callback=self.start_timer)
        self.stop_item = rumps.MenuItem("■ Stop Timer", callback=self.stop_timer)
        self.menu = [
            self.status_item,
            None,
            self.start_item,
            self.stop_item,
            None,
            rumps.MenuItem("Show Touch Bar Timer", callback=self.present_touchbar),
            rumps.MenuItem("Open log file", callback=self.open_log),
            None,
            rumps.MenuItem("Quit SlackTracker", callback=self.quit_app),
        ]
        self.started_at = self.load_state()

        self.touchbar_host = TouchBarHost()
        self.touchbar = None
        if HAVE_TOUCHBAR:
            try:
                self.touchbar = TouchBarController.alloc().initWithTracker_(self)
                if hasattr(NSApp, "setTouchBar_"):
                    NSApp.setTouchBar_(self.touchbar.touch_bar)
                self.touchbar_host.attach_touchbar(self.touchbar.touch_bar)
            except Exception:
                self.touchbar = None
        self._touchbar_requested = False  # set from hotkey thread, consumed on main
        self._toggle_requested = False    # set from SIGUSR2, consumed on main
        self._command_down = False
        self._last_command_tap = 0.0
        self._global_command_monitor = None
        self._local_command_monitor = None
        self._hide_process_requested = True
        self.ui_timer = rumps.Timer(self.ui_tick, 1)
        self.ui_timer.start()

        self._start_hotkey_listener()
        self._install_signal_hooks()
        self.refresh_ui()

    # ---------- state ----------

    @property
    def is_running(self) -> bool:
        return self.started_at is not None

    def load_state(self):
        try:
            state = json.loads(STATE_FILE.read_text())
            return datetime.fromisoformat(state["running_since"])
        except Exception:
            return None

    def save_state(self) -> None:
        state = {"running_since": self.started_at.isoformat()} if self.started_at else {}
        try:
            STATE_FILE.write_text(json.dumps(state, indent=2))
        except Exception:
            pass

    def elapsed(self) -> int:
        if self.started_at is None:
            return 0
        return max(0, int((datetime.now() - self.started_at).total_seconds()))

    # ---------- timer ----------

    def start_timer(self, _):
        if self.is_running:
            return
        self.started_at = datetime.now().replace(microsecond=0)
        self.save_state()
        log_debug(f"Timer started at {self.started_at.isoformat()}")
        self.refresh_ui()

    def stop_timer(self, _):
        if not self.is_running:
            return
        start = self.started_at
        end = datetime.now().replace(microsecond=0)
        self.started_at = None
        self.save_state()
        try:
            seconds = append_period(LOG_FILE, start, end)
            log_debug(f"Timer stopped; logged {fmt_duration(seconds)}")
            rumps.notification("SlackTracker", f"Logged {fmt_duration(seconds)}",
                               f"{start.strftime('%H:%M')} → {end.strftime('%H:%M')} "
                               f"in {LOG_FILE.name}")
        except Exception as exc:
            log_debug(f"Failed to write log: {exc}")
        self.refresh_ui()

    def toggle_timer(self, _):
        if self.is_running:
            self.stop_timer(None)
        else:
            self.start_timer(None)

    # ---------- hotkey ----------

    def _start_hotkey_listener(self):
        if self._start_double_command_listener():
            log_debug("Double-Command shortcut registered")
        else:
            log_debug("Double-Command shortcut unavailable; using fallback chord")

        # Keep the old chord as a fallback; the primary shortcut is Command, Command.
        if self._start_carbon_hotkey_listener():
            return
        self._start_pynput_hotkey_listener()

    def _start_pynput_hotkey_listener(self) -> None:
        if not HAVE_PYNPUT:
            return
        def on_activate():
            # pynput callback runs on its own thread; defer UI work to main.
            self._touchbar_requested = True

        def runner():
            try:
                with pkeyboard.GlobalHotKeys({FALLBACK_HOTKEY: on_activate}) as h:
                    h.join()
            except Exception:
                pass

        t = threading.Thread(target=runner, daemon=True)
        t.start()

    def _start_double_command_listener(self) -> bool:
        if not HAVE_APPKIT:
            return False

        def handle_flags(event):
            try:
                flags = int(event.modifierFlags())
                command_down = bool(flags & NSEventModifierFlagCommand)
                if command_down and not self._command_down:
                    now = monotonic()
                    if now - self._last_command_tap <= DOUBLE_COMMAND_SECONDS:
                        log_debug("Double-Command activated")
                        self._last_command_tap = 0.0
                        self._touchbar_requested = True
                    else:
                        self._last_command_tap = now
                self._command_down = command_down
            except Exception as exc:
                log_debug(f"Double-Command handler failed: {exc}")
            return event

        try:
            self._global_command_monitor = NSEvent.addGlobalMonitorForEventsMatchingMask_handler_(
                NSEventMaskFlagsChanged, handle_flags
            )
            self._local_command_monitor = NSEvent.addLocalMonitorForEventsMatchingMask_handler_(
                NSEventMaskFlagsChanged, handle_flags
            )
            return self._global_command_monitor is not None or self._local_command_monitor is not None
        except Exception as exc:
            log_debug(f"Double-Command setup failed: {exc}")
            return False

    def _start_carbon_hotkey_listener(self) -> bool:
        if os.uname().sysname != "Darwin":
            return False

        class EventTypeSpec(ctypes.Structure):
            _fields_ = [("eventClass", ctypes.c_uint32), ("eventKind", ctypes.c_uint32)]

        class EventHotKeyID(ctypes.Structure):
            _fields_ = [("signature", ctypes.c_uint32), ("id", ctypes.c_uint32)]

        def fourcc(value: str) -> int:
            return int.from_bytes(value.encode("ascii"), "big")

        try:
            carbon = ctypes.cdll.LoadLibrary(
                "/System/Library/Frameworks/Carbon.framework/Carbon"
            )
            self._carbon = carbon
            handler_type = ctypes.CFUNCTYPE(
                ctypes.c_int, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p
            )

            def handler(next_handler, event, user_data):
                log_debug("Carbon hotkey activated")
                self._touchbar_requested = True
                return 0

            self._carbon_hotkey_handler = handler_type(handler)
            event_spec = EventTypeSpec(fourcc("keyb"), 5)  # kEventHotKeyPressed

            carbon.GetApplicationEventTarget.restype = ctypes.c_void_p
            target = carbon.GetApplicationEventTarget()

            carbon.InstallEventHandler.argtypes = [
                ctypes.c_void_p,
                handler_type,
                ctypes.c_uint32,
                ctypes.POINTER(EventTypeSpec),
                ctypes.c_void_p,
                ctypes.POINTER(ctypes.c_void_p),
            ]
            self._carbon_event_handler_ref = ctypes.c_void_p()
            status = carbon.InstallEventHandler(
                target,
                self._carbon_hotkey_handler,
                1,
                ctypes.byref(event_spec),
                None,
                ctypes.byref(self._carbon_event_handler_ref),
            )
            if status != 0:
                log_debug(f"Carbon InstallEventHandler failed: {status}")
                return False

            hotkey_id = EventHotKeyID(fourcc("SlTk"), 1)
            self._carbon_hotkey_ref = ctypes.c_void_p()
            carbon.RegisterEventHotKey.argtypes = [
                ctypes.c_uint32,
                ctypes.c_uint32,
                EventHotKeyID,
                ctypes.c_void_p,
                ctypes.c_uint32,
                ctypes.POINTER(ctypes.c_void_p),
            ]
            status = carbon.RegisterEventHotKey(
                CARBON_HOTKEY_KEYCODE,
                CARBON_HOTKEY_MODIFIERS,
                hotkey_id,
                target,
                0,
                ctypes.byref(self._carbon_hotkey_ref),
            )
            if status != 0:
                log_debug(f"Carbon RegisterEventHotKey failed: {status}")
                return False
            log_debug("Carbon hotkey registered: Ctrl+Option+Cmd+T")
            return True
        except Exception as exc:
            log_debug(f"Carbon hotkey setup failed: {exc}")
            return False

    def _install_signal_hooks(self) -> None:
        try:
            signal.signal(signal.SIGUSR1, self._handle_show_signal)
            signal.signal(signal.SIGUSR2, self._handle_toggle_signal)
        except Exception:
            pass

    def _handle_show_signal(self, signum, frame) -> None:
        log_debug("SIGUSR1 Touch Bar request")
        self._touchbar_requested = True

    def _handle_toggle_signal(self, signum, frame) -> None:
        log_debug("SIGUSR2 start/stop request")
        self._toggle_requested = True

    # ---------- UI loop ----------

    def ui_tick(self, _):
        # Consume shortcut / signal requests on the main thread.
        if self._touchbar_requested:
            self._touchbar_requested = False
            self.present_touchbar(None)
        if self._toggle_requested:
            self._toggle_requested = False
            self.toggle_timer(None)

        self.refresh_ui()
        if self._hide_process_requested:
            self._hide_process_requested = False
            self.hide_from_dock()

    def hide_from_dock(self) -> None:
        try:
            NSApp.setActivationPolicy_(NSApplicationActivationPolicyAccessory)
            NSRunningApplication.currentApplication().hide()
        except Exception:
            pass
        try:
            subprocess.run(
                [
                    "osascript",
                    "-e",
                    (
                        'tell application "System Events" to set visible of '
                        f'(first process whose unix id is {os.getpid()}) to false'
                    ),
                ],
                capture_output=True,
                timeout=3,
            )
        except Exception:
            pass

    def refresh_ui(self):
        if self.is_running:
            clock = fmt_clock(self.elapsed())
            self.title = f"⏱ {clock}"
            self.status_item.title = (
                f"Running since {self.started_at.strftime('%H:%M:%S')} — {clock}"
            )
        else:
            self.title = "⏱"
            self.status_item.title = "Timer stopped"
        # rumps disables items whose callback is None.
        self.start_item.set_callback(None if self.is_running else self.start_timer)
        self.stop_item.set_callback(self.stop_timer if self.is_running else None)
        if self.touchbar:
            self.touchbar.update()

    # ---------- menu actions ----------

    def present_touchbar(self, _):
        log_debug("Touch Bar timer requested")
        if self.touchbar:
            self.touchbar_host.attach_touchbar(self.touchbar.touch_bar)
            self.touchbar_host.present()
            self.touchbar.present()
        else:
            log_debug("Touch Bar unavailable on this Mac or PyObjC install")

    def open_log(self, _):
        if not LOG_FILE.exists():
            LOG_FILE.write_text("# Work Log\n\nGenerated by SlackTracker.\n")
        subprocess.run(["open", str(LOG_FILE)])

    def quit_app(self, _):
        rumps.quit_application()


if __name__ == "__main__":
    SlackTracker().run()
